# Script PowerShell para verificar y corregir la configuración del Android SDK

Write-Host "🔍 Verificando configuración del Android SDK..." -ForegroundColor Cyan
Write-Host ""

$localPropertiesPath = "android\local.properties"
$sdkPath = "C:\Users\User\AppData\Local\Android\Sdk"

# Verificar si el archivo existe
if (Test-Path $localPropertiesPath) {
    Write-Host "✅ Archivo local.properties encontrado" -ForegroundColor Green
    $content = Get-Content $localPropertiesPath -Raw
    Write-Host "Contenido actual:" -ForegroundColor Yellow
    Write-Host $content
    Write-Host ""
} else {
    Write-Host "❌ Archivo local.properties no encontrado" -ForegroundColor Red
    Write-Host "Creando archivo..." -ForegroundColor Yellow
}

# Verificar si la ruta del SDK existe
if (Test-Path $sdkPath) {
    Write-Host "✅ SDK encontrado en: $sdkPath" -ForegroundColor Green
} else {
    Write-Host "❌ SDK NO encontrado en: $sdkPath" -ForegroundColor Red
    Write-Host ""
    Write-Host "💡 Buscando SDK en otras ubicaciones comunes..." -ForegroundColor Yellow
    
    $alternativePaths = @(
        "$env:LOCALAPPDATA\Android\Sdk",
        "$env:USERPROFILE\AppData\Local\Android\Sdk",
        "C:\Program Files\Android\android-sdk",
        "$env:ANDROID_HOME",
        "$env:ANDROID_SDK_ROOT"
    )
    
    $found = $false
    foreach ($path in $alternativePaths) {
        if ($path -and (Test-Path $path)) {
            Write-Host "✅ SDK encontrado en: $path" -ForegroundColor Green
            $sdkPath = $path
            $found = $true
            break
        }
    }
    
    if (-not $found) {
        Write-Host ""
        Write-Host "❌ No se encontró el Android SDK" -ForegroundColor Red
        Write-Host ""
        Write-Host "📋 Soluciones:" -ForegroundColor Yellow
        Write-Host "1. Instala Android Studio: https://developer.android.com/studio"
        Write-Host "2. O configura manualmente la ruta en android/local.properties"
        Write-Host ""
        exit 1
    }
}

# Crear o actualizar local.properties
$sdkDir = $sdkPath.Replace('\', '/')
$propertiesContent = "## This file is automatically generated.`n# Do not modify this file -- YOUR CHANGES WILL BE ERASED!`n#`n# Location of the SDK. This is only used by Gradle.`nsdk.dir=$sdkDir`n"

Set-Content -Path $localPropertiesPath -Value $propertiesContent -Encoding UTF8
Write-Host ""
Write-Host "✅ Archivo local.properties actualizado" -ForegroundColor Green
Write-Host "   SDK: $sdkPath" -ForegroundColor Cyan
Write-Host ""
Write-Host "Ahora puedes ejecutar: npm run apk" -ForegroundColor Yellow
Write-Host ""

